language: node_js
node_js:
  - '10'
dist: trusty
os: Linux
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install codecov -g
  - npm ci --ignore-scripts
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
  # run build script specified in package.json
  - npm run ci
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh
after_success:
  - codecov
